name: "🔥 HEARTH CTI Submission"
description: "Submit a piece of Cyber Threat Intelligence (CTI) to be processed into a HEARTH hunt."
title: "CTI Submission: [Threat Actor, Malware, or Report Name]"
labels: ["intel-submission", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to HEARTH! Please provide the CTI details below.

  - type: textarea
    id: cti-content
    attributes:
      label: "CTI Content"
      description: "This will be populated automatically by our backend process. You can leave this empty."
      value: "*(This will be processed automatically by our system. Please leave this section as is.)*"
    validations:
      required: false

  - type: input
    id: cti-source
    attributes:
      label: "Link to Original Source"
      description: "Provide a link to the original CTI report or article."
      placeholder: "https://example.com/report.pdf"
    validations:
      required: false

  - type: input
    id: submitter-name
    attributes:
      label: "Your Name / Handle"
      description: "How you would like to be credited for this submission."
      placeholder: "e.g., Jane Doe"
    validations:
      required: false

  - type: input
    id: submitter-link
    attributes:
      label: "Link to Profile (Optional)"
      description: "A link to your professional profile (e.g., GitHub, Twitter, LinkedIn)."
      placeholder: "https://github.com/janedoe"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        *By submitting this issue, you agree to our contribution guidelines.* 