name: "🔥 HEARTH CTI Submission"
description: "Submit a piece of Cyber Threat Intelligence (CTI) to be processed into a HEARTH hunt."
title: "CTI Submission: [Threat Actor, Malware, or Report Name]"
labels: ["intel-submission", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to HEARTH! Please provide the CTI details below.
        **To attach a file (PDF, TXT, etc.), simply drag and drop it into the 'Pasted CTI' text box below.**

  - type: textarea
    id: cti-paste
    attributes:
      label: "Upload CTI File or Paste Text"
      description: "Drag & drop a file here to upload it, or paste the raw CTI text directly."
      render: markdown
    validations:
      required: false

  - type: input
    id: cti-link
    attributes:
      label: "Or Provide a Public Link to CTI"
      description: "If you cannot upload the file, you can provide a direct, public link to it (e.g., a PDF link)."
      placeholder: "https://example.com/report.pdf"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        *By submitting this issue, you agree to our contribution guidelines.* 