name: "🔥 HEARTH CTI Submission"
description: "Submit a piece of Cyber Threat Intelligence (CTI) to be processed into a HEARTH hunt."
title: "CTI Submission: [Threat Actor, Malware, or Report Name]"
labels: ["intel-submission", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to HEARTH! Please provide the CTI details below.
        You can either upload a file OR provide a public link to the report.

  - type: textarea
    id: cti-paste
    attributes:
      label: "Upload CTI File or Paste Text"
      description: "Drag & drop a file here to upload it, or paste the raw CTI text directly. This is the recommended method."
      render: markdown
    validations:
      required: false

  - type: input
    id: cti-link
    attributes:
      label: "OR Provide a Public Link to the CTI Report"
      description: "If you cannot upload a file, provide a direct, public link to the report. The link must be accessible without authentication."
      placeholder: "https://example.com/report.pdf"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        *By submitting this issue, you agree to our contribution guidelines.* 