name: Manual Hunt Submission
description: Submit a pre-formed threat hunt idea for formatting and inclusion.
title: "Manual Hunt: [Your Hunt Title Here]"
labels: ["manual-submission"]
body:
  - type: markdown
    attributes:
      value: |
        ## Manual Hunt Submission
        Use this form to submit a threat hunt idea that you have already partially or fully developed. Our automation will format it into the standard HEARTH format.

  - type: textarea
    id: hypothesis
    attributes:
      label: Hunt Hypothesis
      description: "Provide the core hypothesis for your hunt. This should be a specific, actionable statement."
      placeholder: "e.g., Adversaries are creating scheduled tasks with random 8-character alphanumeric names to execute Base64-encoded PowerShell commands at system startup."
    validations:
      required: true

  - type: input
    id: tactic
    attributes:
      label: MITRE ATT&CK Tactic
      description: "The primary MITRE Tactic (e.g., Persistence, Defense Evasion)."
      placeholder: "Persistence"
    validations:
      required: true

  - type: input
    id: technique
    attributes:
      label: MITRE ATT&CK Technique ID
      description: "The specific MITRE Technique ID (e.g., T1053.005)."
      placeholder: "T1053.005"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this hunt important?
      description: "Explain the significance of this hunt. What is the impact? Does it relate to a known threat actor or campaign?"
      placeholder: "- Detects a common persistence mechanism used by TrickBot.\n- Helps identify evasive scheduled tasks that might be missed by standard security tools."
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: "Provide any relevant links, such as the source CTI report or a link to the MITRE ATT&CK technique page."
      placeholder: "- https://attack.mitre.org/techniques/T1053/005/\n- https://www.mandiant.com/resources/blog/trickbot-deep-dive"
    validations:
      required: true

  - type: input
    id: submitter-name
    attributes:
      label: Your Name / Handle
      description: "How you would like to be credited."
    validations:
      required: true

  - type: input
    id: submitter-link
    attributes:
      label: Link to Profile (Optional)
      description: "Link to your Twitter, GitHub, LinkedIn, etc." 