name: "Create PR from Approved Draft"

on:
  issues:
    types: [labeled]

jobs:
  create_pr:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: "Create Pull Request"
        id: create_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.HEARTH_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const branchName = `draft/issue-${issueNumber}`;
            
            try {
              // Check if the branch exists and has differences from main
              const { data: compareData } = await github.rest.repos.compareCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: 'main',
                head: branchName
              });
              
              if (compareData.ahead_by === 0) {
                core.setFailed(`Branch ${branchName} has no differences from main. Cannot create PR.`);
                return;
              }
              
              // Create the pull request
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `🔥 Hunt from Issue #${issueNumber}`,
                body: `This PR was automatically generated from an approved submission in issue #${issueNumber}.\n- **Submitter**: @${context.issue.user.login}\n- **Source Issue**: #${issueNumber}\n\nCloses #${issueNumber}`,
                head: branchName,
                base: 'main'
              });
              
              // Add labels and assignees
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['needs-review', 'automated-pr']
              });
              
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                assignees: [context.issue.user.login]
              });
              
              core.setOutput('pull-request-number', pr.number);
              console.log(`✅ Created PR #${pr.number} from branch ${branchName}`);
              
            } catch (error) {
              console.error('Error creating PR:', error);
              core.setFailed(`Failed to create PR: ${error.message}`);
            }

      - name: "Comment on issue with PR link"
        if: steps.create_pr.outputs.pull-request-number
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.HEARTH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            🚀 Your submission has been approved and a pull request has been created. Thank you!
            🔗 **View PR**: #${{ steps.create_pr.outputs.pull-request-number }} 