name: "Draft Hunt from Manual Submission"

on:
  issues:
    types: [labeled]

jobs:
  create_manual_draft:
    if: github.event.label.name == 'manual-submission'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Git Branch"
        run: |
          git checkout -b draft/issue-${{ github.event.issue.number }}

      - name: "Set up Python 3"
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install openai python-dotenv

      - name: "Run HEARTH manual processor"
        id: generate_draft_file
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: python scripts/process_manual_submission.py

      - name: "Commit and push generated hunt"
        run: |
          git config --global user.name 'hearthbot'
          git config --global user.email 'hearthbot@users.noreply.github.com'
          git add Flames/*.md
          git commit -m "feat(draft): Create manual hunt from issue #${{ github.event.issue.number }}"
          git remote set-url origin https://x-access-token:${{ secrets.HEARTH_TOKEN }}@github.com/${{ github.repository }}
          git push --set-upstream origin draft/issue-${{ github.event.issue.number }}

      - name: "Comment on issue with draft link"
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.HEARTH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ A new hunt has been drafted from your manual submission. Thank you for contributing!
            
            Please review the formatted file here:
            [**View Hunt Draft**](https://github.com/${{ github.repository }}/blob/draft/issue-${{ github.event.issue.number }}/${{ steps.generate_draft_file.outputs.HUNT_FILE_PATH }})
            
            If it looks good, add the `approved` label. 