name: Scheduled HEARTH Draft Generation

# Runs at 16:00 UTC every day (that’s 9 AM America/Phoenix time)
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  generate-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-dotenv

      - name: Run HEARTH draft generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/generate_from_cti.py

      - name: Commit generated drafts
        run: |
          git config user.name "hearthbot"
          git config user.email "hearthbot@users.noreply.github.com"
          git add .hearth/auto-drafts/*.md || echo "No new drafts"
          git commit -m "chore: scheduled HEARTH draft run" || echo "Nothing to commit"
          git push

      - name: Open PR for review
        uses: peter-evans/create-pull-request@v5
        with:
          title: "HEARTH scheduled draft — needs review"
          body: |
            This hunting draft was auto-generated on schedule. Please review and merge when ready.
          branch: scheduled-drafts-${{ github.run_number }}
          base: main
          labels: needs-review
          assignees: YOUROGUSERNAME
