name: Update Hunt Database

on:
  push:
    branches:
      - main
    paths:
      - 'Flames/**.md'
      - 'Embers/**.md'
      - 'Alchemy/**.md'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script to update hunt data
        run: python3 scripts/parse_hunts.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add hunts-data.js
          # Commit only if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "chore: Auto-update hunt database"
            git push
          else
            echo "No changes to commit."
          fi 