name: "Update Contributor Leaderboard"

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the 1st of every month

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4

      - name: "Set up Python 3"
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: "Run leaderboard generator"
        run: python HEARTH/scripts/generate_leaderboard.py
      
      - name: "Commit and push if changed"
        run: |
          git config --global user.name 'hearthbot'
          git config --global user.email 'hearthbot@users.noreply.github.com'
          git add HEARTH/Keepers/Contributors.md
          # The following command will fail if there are no changes, which is fine.
          # We use `|| true` to ensure the workflow doesn't fail if the commit is empty.
          git commit -m "chore: update contributor leaderboard" || true
          git push origin main || true 